require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'AppcuesReactNativeSdkExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false,
  )

  # Have to manually add Appcues here until the Podspec is published so that `pod install` knows where to find it
  pod 'Appcues', :path => '../../../appcues-ios-sdk/Appcues.podspec'

  pod 'appcues-react-native-sdk', :path => '../..'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
